### ISSUE TITLE
On/Off 상태가 제대로 변경되지 않습니다.

### ISSUE THREAD

**Issue by Murianwind** [oukene/state_switch#1]
2290dd2 빌드까지는 분명 제대로 반영이 되었었는데...

718f131 빌드부터는 제대로 반영이 되지 않습니다.

Home Assistant 2023.1.1
Supervisor 2022.12.1
Operating System 9.4
Frontend 버전: 20230104.0 - latest

이고..

- platform: state_switch
  switches:
    monitor_switch:
      friendly_name: TV 전원
      unique_id: monitor_switch
      icon_template: mdi:monitor
      on_off_delay: 10000
      value_template: "{{ states('sensor.plug_monitor_usage')|float(0) > 5 }}"
      turn_on:
        service: rest_command.switchbot_scene_command
        data:
          sceneId: !secret power_sceneId
      turn_off:
        service: rest_command.switchbot_scene_command
        data:
          sceneId: !secret power_sceneId

이렇게 만들었는데..

예를 들면 On 상태를 누르면 On 상태로 변경되었다가 바로 Off 상태로 스위치 상태가 변경되어 버립니다.

그리고 10초후에 On 상태로 변경되거나 경우에 따라서는 변경되지 않는 경우도 있습니다.

변경되지 않는 경우에 해당하는 로그나 조건을 찾아봐도 특정한 문제를 찾지 못했습니다.

기대했던거는 이전처럼 On 상태를 누르면 On 상태로 변경된 상태를 유지하다가 10초 후에 조건 값에 따라 On을 유지하거나 Off로 변경되는건데..

한번 살펴봐 주실 수 있을까요?

**Comment by Murianwind** [comment]
https://user-images.githubusercontent.com/6447460/211138755-0a4bdfc4-cef8-4ec9-8d86-2d5dc39e6e7a.mp4

**Comment by Murianwind** [comment]
동영상에서 보시는 것처럼 On/Off 기준값이 되는 실시간 전력 사용량 값이 조건을 만족함에도 상태가 한번 변경되었다가 다시 반영됩니다.

**Comment by oukene** [comment]
업데이트 한번 받아보세요

**Comment by Murianwind** [comment]
> 업데이트 한번 받아보세요

업데이트 후 반복 테스트 해본 결과입니다.

1. 템플릿 스위치 UI에서 On 또는 Off 를 선택했을 때 스위치가 반복 선택됩니다. 그러니까 만약에 Off에서 On으로 선택하면 스위치가 On-Off-On 이런식으로 깜박입니다. 그런데, 스위치 UI가 아닌 스크립트나 다른 외부 스위치에서 서비스를 호출했을 때는 그런 현상이 발생하지 않습니다. 제 기억이 정확하다면 초기 버전에서는 이런 문제가 없었던 것 같은데.. 이유를 모르겠습니다. 

2. 지연 시간을 예로 들어 10초를 주고.. Off 에서 On으로 변경했다가 지연 시간 이내 그러니까 10초 이내에서 다시 Off로 선택하는 경우 첫번째 지연만 인식되고 두번째 지연이 인식되지 않는 것 같습니다. 그러니까 Off 에서 On으로 변경했다가 10초 이내에 다시 Off로 선택하는 경우 실시간 전력 값이 미처 변경되지 않는다면 (MQTT의 인터벌이 있기 때문에 시간 차로 어긋나버리면) 첫번째 Off 에서 10초를 계산해서 On으로 인식하고 Off를 On으로 바꾸어버립니다. 그 상태에서 2번째 변경에 대해 10초 이후가 되어서 전력 값이 Off 조건을 만족해도 스위치는 On을 유지합니다. 지연을 계산하는 시간이 마지막 스위치 값이 변경된 시점으로 재시작 되거나 일정 시간마다 값을 확인해서 스위치 값을 바꾸거나 하는게 덧 낫지 않을까 싶습니다.

**Comment by Murianwind** [comment]
https://user-images.githubusercontent.com/6447460/211152609-26a0716a-bdd1-4f5f-bf1f-f7c5cd009811.mp4

**Comment by oukene** [comment]
저는 문제 없이 의도한대로 잘 작동 하고 있습니다

아니네요, 조금 문제가 있네요

**Comment by oukene** [comment]
그런데 저는 동영상 올리신것처럼 저런 증상은 없는데, 전력량이 실시간이 아닌건가요? 저는 선풍기로 테스트 하니까 끌때 전력사용량이 좀 늦게 떨어져서 그렇지 10초 정도 하니 의도한대로 작동됩니다. 올리신 동영상으로는 무슨 상황인지 잘 모르겠네요

**Comment by Murianwind** [comment]
> 

전력량을 30초마다 한번씩 갱신하도록 되어 있어서 딜레이 시간은 제가 조정하면 되는거라 문제는 아닙니다.

제가 제시하는 의견은..

1. HA 웹 화면의 센서 UI에서 예를 들면 Off에서 On으로 변경할 때 UI상으로 Off에서 On으로 변경되었다가 바로 다시 Off로 그 다음에 다시 On으로 깜박거리는 현상이 발생합니다. 위 동영상에서도 보실 수 있습니다. 그러니까 Off 에서 On으로 변경하면 스위치가 그 상태를 지연 시간동안 유지하다가 지연 시간 이후에 조건이 충족되지 않는다면 다시 스위치가 변경되어야 하는데.. 더블 클릭한거처럼 깜박이는 현상이 발생합니다. 그런데.. 이게 센서의 스위치를 직접 조작할 때만 발생하고 자동화나 스크립트로 서비스를 호출하는 경우에는 발생하지 않습니다. 그리고 스위치 설정에서 value_template을 제거해도 이 현상은 발생하지 않습니다. 이게 HA 고유 문제라면 신경 쓰지 않으셔도 됩니다.

2. 두번째는 저 같은 경우에는 실시간 전력값을 30초마다 갱신하게 되어 있는데.. 예를 들면, Off에서 On으로 변경하고 나면 지연 시간 30초가 카운팅이 될겁니다. 그런데, 제가 카운팅이 끝나기 전에 예를 들면, 10초 후에 다시 Off로 변경하면 제가 스위치를 변경한 시점에서 다시 카운팅이 시작되는게 아니라.. 10초 전의 스위치를 On으로 했던 카운팅이 계속 진행되고 있고.. 그 상태로 20초 뒤가 되면 전력량 값이 아직 Off 상태로 갱신되어 있지 않기 때문에 스위치가 On으로 변경됩니다. 그러면 실제 스위치는 Off 상태인데.. 표시는 On 상태가 유지되어 버립니다. 그러니까 지연 시간 카운팅이 최종 스위치 변경 시점부터 재시작이 되어야 하는데.. 지연 시간 카운팅 중에 스위치 값이 변경되면 그걸 인식을 하지 않습니다.
머.. 이것도 성질 급한 제 문제이기는 하지만 한번 살펴봐 주시면 감사하겠습니다.

**Comment by oukene** [comment]
1. 저는 그렇게 작동 되고 있습니다.
2. 지금 그렇게 만들어져 있습니다

**Comment by oukene** [comment]
input_number 를 하나 만들고  그 값을 기준으로 상태를 변경하는 스위치를 하나 만들어서 테스트 한번 해보세요

**Comment by Murianwind** [comment]
> input_number 를 하나 만들고 그 값을 기준으로 상태를 변경하는 스위치를 하나 만들어서 테스트 한번 해보세요

음.. 첫번째는 계속 신경을 거슬리게 하기는 하는데.. HA 고유 문제인가보네요.. 그냥 써야겠네요..

두번째는.. 아무래도 시간 인터벌에서 뭔가 꼬이나보네요.. 좀 더 테스트 해보겠습니다.

남은 주말 즐겁게 보내세요.

**Comment by oukene** [comment]
첫번째 말씀하시는게 저는 발생하지 않아요~ 스위치 켜면 갤홈미니로 IR 선풍기를 켜는데, 5초로 지연을 해놓으면 5초되는 시점에 off 로 살짝 표시되었다가 다시 on 으로 바뀝니다. 10초로 하면 그런 증상이 없어요

그리고 타이머는 스위치를 HA UI 상에서 직접 on , off 할떄 작동하는데 그 전 타이머가 있다면 취소를 시킵니다. 그리고 스위치의 상태값이 value_template 에 의해 변경이 될 떄에도 타이머가 있다면 취소를 하게 되어있습니다

**Comment by Murianwind** [comment]
> 첫번째 말씀하시는게 저는 발생하지 않아요~ 스위치 켜면 갤홈미니로 IR 선풍기를 켜는데, 5초로 지연을 해놓으면 5초되는 시점에 off 로 살짝 표시되었다가 다시 on 으로 바뀝니다. 10초로 하면 그런 증상이 없어요
> 
> 그리고 타이머는 스위치를 HA UI 상에서 직접 on , off 할떄 작동하는데 그 전 타이머가 있다면 취소를 시킵니다. 그리고 스위치의 상태값이 value_template 에 의해 변경이 될 떄에도 타이머가 있다면 취소를 하게 되어있습니다

제 HA만 뭔가 이상한가보네요.. ㅠㅠ

**Comment by oukene** [comment]
그런것보다, 위에 제가 적은대로 input_number 하나 만들어서 기본 테스를 한번 해보시고, 전력량 리포팅 주기가 짧은 플러그를 이용해서 한번 해보시거나 플러그가 없다면 30초 지연 플러그라면 1분 정도로 충분히 설정해놓고, 여유시간을 좀 두면서 기본 동작 부터 한번 테스트 해보세요

물론 코드에 버그가 있을 수도 있는데 저는 잘 돌아가니 확인할 길이 없네요

코드는 최신이 맞는지 한번 확인해보세요, 어제 수정하기 전 버전에서는 충분히 그럴수 있게 만들어져 있었거든요

**Comment by Murianwind** [comment]
> 그런것보다, 위에 제가 적은대로 input_number 하나 만들어서 기본 테스를 한번 해보시고, 전력량 리포팅 주기가 짧은 플러그를 이용해서 한번 해보시거나 플러그가 없다면 30초 지연 플러그라면 1분 정도로 충분히 설정해놓고, 여유시간을 좀 두면서 기본 동작 부터 한번 테스트 해보세요
> 
> 물론 코드에 버그가 있을 수도 있는데 저는 잘 돌아가니 확인할 길이 없네요
> 
> 코드는 최신이 맞는지 한번 확인해보세요, 어제 수정하기 전 버전에서는 충분히 그럴수 있게 만들어져 있었거든요

우선은 머리를 좀 식혔다가 테스트 해보겠습니다.

어제 이거 때문에 수십번을 HA를 재부팅했더니.. 지금 HA 상태도 안좋은 것 같아서.. 주말에 신경 써주셔서 고맙습니다.

컴포넌트는 최신 버전으로 설치되어 있고.. 

그냥 인풋넘버 센서 하나로 멍텅구리를 만들어도 저는 첫번째 문제가 계속 발생하네요.. 음.. 몇일 있다가 다시 해보고 원인을 찾으면 다시 올려보겠습니다.

**Comment by oukene** [comment]
에고 괜히 이런 걸 만들어서 힘들게 해드렸네요, "그냥 인풋넘버 센서 하나로 멍텅구리를 만들어도 저는 첫번째 문제가 계속 발생하네요.." -> 스위치 on 한 다음에 시간 내에 input_number 수치를 기준치 이상으로 변경하면 스위치 상태가 유지되어야 정상입니다.

**Comment by Murianwind** [comment]
> 에고 괜히 이런 걸 만들어서 힘들게 해드렸네요, "그냥 인풋넘버 센서 하나로 멍텅구리를 만들어도 저는 첫번째 문제가 계속 발생하네요.." -> 스위치 on 한 다음에 시간 내에 input_number 수치를 기준치 이상으로 변경하면 스위치 상태가 유지되어야 정상입니다.

아뇨.. 이렇게 만들어주셔서 아주 깊이 감사한 마음으로 사용하고 있습니다. 제가 다시 한번 더 찬찬히 확인해보겠습니다. 남은 주말 편하게 쉬시기 바랍니다.

**Comment by Murianwind** [comment]
> 에고 괜히 이런 걸 만들어서 힘들게 해드렸네요, "그냥 인풋넘버 센서 하나로 멍텅구리를 만들어도 저는 첫번째 문제가 계속 발생하네요.." -> 스위치 on 한 다음에 시간 내에 input_number 수치를 기준치 이상으로 변경하면 스위치 상태가 유지되어야 정상입니다.

첫번째 문제의 원인을 찾았습니다. HACS에 custom-ui라는 컴포넌트가 있는데.. 이 설정과 뒤엉켜서 일어나는 현상이었습니다.
custom-ui를 제거하고 캐시 제거하고 재설정하니 정상적으로 동작을 합니다.

주말에 별것 아닌 문제로 번거롭게 해드려서 죄송합니다. 이번 한주도 즐거운 한주 되시길 바랍니다.
